# Generated by Django 2.1 on 2018-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotwizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
