# Generated by Django 2.1 on 2018-09-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotwizard', '0002_auto_20180907_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataline',
            options={'ordering': ['id']},
        ),
    ]
